local user="%{$fg[magenta]%}%n@%{$fg_bold[blue]%}%m%{$reset_color%}"
local return_code="%(?:%{$fg_bold[green]%}%1{➜%} :%{$fg_bold[red]%}%? %1{➜%} )"
local pwd="%{$fg[cyan]%}%c%{$reset_color%}"
PROMPT="${user} ${return_code} ${pwd}"
PROMPT+=' $(git_prompt_info)'
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}%1{✗%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
