### Variables
#
# Logo key. Use Mod1 for Alt.
set $mod Mod4

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

# Your preferred terminal emulator
set $term kitty 

# Font
font pango: SourceCodePro Medium 12

# Your preferred application launcher
# Note: pass the final command to swaymsg so that the resulting window can be opened
# on the original workspace that the command was run on.
set $menu fuzzel | xargs swaymsg exec --

# Setup wob (overlay bar)
set $WOBSOCK $XDG_RUNTIME_DIR/wob.sock

# Set locking method
set $chill_lock "swaylock --screenshots --clock --indicator --effect-pixelate 10 --effect-greyscale --fade-in 5"
set $hard_lock "swaylock --clock --indicator --image $wallpaper"

