# Disable highlight copy and middle click paste by immediately erasing the primary clipboard
exec /home/carlo/.config/sway/scripts/disable-primary-paste.sh

# Clipboard manager cliphist for regular clipboard
exec cliphist wipe
exec "wl-paste --watch cliphist store"
set $clipboard cliphist list | fuzzel -d -p "copy: " | cliphist decode | wl-copy
set $clipboard-del cliphist list | fuzzel -d -p "delete: " | cliphist delete && pkill -RTMIN+9 waybar
set $clipboard-del-all cliphist wipe; pkill -RTMIN+9 waybar


# Wayland bar wob
exec rm -f $WOBSOCK && mkfifo $WOBSOCK && tail -f $WOBSOCK | wob

# Execute gammastep-indicator on startup
exec gammastep-indicator -c .config/gammastep/config.ini

# Start SOV pipeline
exec "rm -f /tmp/sovpipe && mkfifo /tmp/sovpipe && tail -f /tmp/sovpipe | sov -t 500"

# Enable Wayland
xwayland enable

# See which window is using XWayland
for_window [shell="xwayland"] title_format "[XWayland] %title"

# Notification Daemon
exec swaync

### Idle configuration
#
# Example configuration:
#
exec swayidle -w \
         timeout 1800 exec $chill_lock \
         timeout 3600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep exec $chill_lock

# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.

# Start the keyboard layout notification daemon
exec_always "/home/carlo/.config/sway/scripts/keyboard_layout_notify.sh"
